In [1]:
#importando a blibloteca numpy
import numpy as np

In [4]:
#declarando variaveis de km e anos
km = np.array([44410., 5712., 37123., 0., 25757.])

anos = np.array([2003, 1991, 1990, 2019, 2006])

In [6]:
#calculo de idade 
idade = 2019 - anos
idade

array([16, 28, 29,  0, 13])

In [7]:
#km_media calculo
km_media = km / idade

km_media

C:\Users\walla\AppData\Local\Temp\ipykernel_113928\661698549.py:1: RuntimeWarning: invalid value encountered in divide
  km_media = km / idade


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [9]:
#declarando array com variavel dados
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [10]:
#media de km buscando por dados
km_media = dados[0] / (2019 - dados[1])
km_media

C:\Users\walla\AppData\Local\Temp\ipykernel_113928\4063055428.py:1: RuntimeWarning: invalid value encountered in divide
  km_media = dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])