In [2]:
#importando a blibloteca numpy
import numpy as np

In [3]:
#declarando variaveis de km e anos
km = np.array([44410., 5712., 37123., 0., 25757.])

anos = np.array([2003, 1991, 1990, 2019, 2006])

In [4]:
#calculo de idade 
idade = 2019 - anos
idade

array([16, 28, 29,  0, 13])

In [5]:
#km_media calculo
km_media = km / idade

km_media

C:\Users\walla\AppData\Local\Temp\ipykernel_129840\3626675495.py:2: RuntimeWarning: invalid value encountered in divide
  km_media = km / idade


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [6]:
#declarando array com variavel dados
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [7]:
#media de km buscando por dados
km_media = dados[0] / (2019 - dados[1])
km_media

C:\Users\walla\AppData\Local\Temp\ipykernel_129840\4139559335.py:2: RuntimeWarning: invalid value encountered in divide
  km_media = dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [8]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.], [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [9]:
dados.shape

(2, 5)

In [10]:
dados.ndim

2

In [11]:
dados.size

10

In [12]:
dados.dtype

dtype('float64')

In [13]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [14]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [15]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [16]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
contador.reshape((5, 2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [20]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [21]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [23]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [24]:
np.array(info_carros)

array([44410,  5712, 37123,     0, 25757,  2003,  1991,  1990,  2019,
        2006])

In [25]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [26]:
np.array(info_carros).reshape((5, 2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [27]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [30]:
dados_new.resize((3, 5), refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [31]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])
dados_new

C:\Users\walla\AppData\Local\Temp\ipykernel_129840\3664879450.py:1: RuntimeWarning: invalid value encountered in divide
  dados_new[2] = dados_new[0] / (2019 - dados_new[1])


array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])